Use JRC-IDEES thermal energy service instead of FE for buildings heating demand
PyPSA/pypsa-eur pull request #1255
Opened 2024-09-02 17:46 UTC by nworbmot

This change consists of:

- reading the final energy (FE) to thermal energy service (TES) efficiency for each each country from JRC-IDEES, separately for gas and oil (this efficiency represents e.g. the losses in older non-condensing boilers, averaging around 20% in 2020)

- the efficiencies are stored in `resources/heating_efficiencies.csv` for different years and countries

- using TES instead of FE for the heat demand in n.loads_t, so that it is pure energy service instead of including losses in legacy equipment

- using the stored boiler efficiencies for baseyear equipment in `add_existing_baseyear.py`

In the baseyear (e.g. 2020) this should have no effect on FE, since the reduction to TES is compensated by the lower efficiencies of existing equipment.

In the future (e.g. 2050) this leads to a reduction in heating demand, since new equipment is more efficient than existing.

The following documents changes to results for a 45-node 3H simulation with the myopic code and investment years 2020 and 2050.

The change reduces the heat demand by 19% in 2020 and 20% in 2050:

![image](https://github.com/user-attachments/assets/d86c6232-9e36-47f7-a9d3-3099710072d0)

The fraction of heat provided by gas boilers actually goes down, since some is substituted by biomass boilers and heat pumps:

![image](https://github.com/user-attachments/assets/22bddb51-32c0-4c92-bf28-4d22fdbf3e40)

![image](https://github.com/user-attachments/assets/3f34b902-8161-41d5-b0d4-48b579bc0347)

Gas boiler average efficiency drops from 97% to 78%, while oil boiler average efficiency drops from 90% to 62%.

This means that the effects of lower demand by 19% but including boiler losses better doesn't quite cancel out, because some of the gas demand is eaten by biomass boilers and heat pumps. Here is the gas boiler gas consumption:

![image](https://github.com/user-attachments/assets/e170a517-df90-4396-bc23-8395567d6e66)

Closes [#540](https://github.com/PyPSA/pypsa-eur/issues/540).

## Changes proposed in this Pull Request

## Checklist

- [x] I tested my contribution locally and it seems to work fine.
- [x] Code and workflow changes are sufficiently documented.
- [x] Changed dependencies are added to `envs/environment.yaml`.
- [x] Changes in configuration options are added in all of `config.default.yaml`.
- [x] Changes in configuration options are also documented in `doc/configtables/*.csv`.
- [ ] A release note `doc/release_notes.rst` is added.

2024-09-09 16:31 UTC, lisazeyen commented
one thought @nworbmot : in `prepare_sector_network` the thermal energy service (TES) is added as the heating demand. This heating demand is split into individual and district heating. In `add_existing_baseyear` the efficiencies for individual heating for existing assets are used, while for district heating the efficiencies of the technology data are used. This lead for district heating networks in e.g. 2020 that final energy consumption from JRC-IDEES is unequal to our assumptions.

2024-09-10 15:02 UTC, nworbmot commented
I agree this will lead to a ~10% underestimation of district heating demand, which we should fix at a later point, but we should pull this PR now so we get the benefit for individual heating (~20% reduction of FE in 2050). 20% is a bigger effect that 10%*10% (error times 10% DH share)  = 1%. I'm trying to think what the best way is to solve this really properly - we need to probably separate out the DH share at the beginning somehow.

2024-09-10 16:29 UTC, lisazeyen approved these changes

2024-09-10 19:24 UTC, fneum requested changes
Semantically, looks good to me. Some code fixes required before merging:

2024-09-10 19:24 UTC, fneum commented on scripts/add_existing_baseyear.py
> +        ).loc[int(snakemake.config["energy"]["energy_totals_year"])]
`snakemake.config` should no longer be used in `scripts/*.py` files due to new scenario management.

```suggestion
        fn = snakemake.input.heating_efficiencies
        year = int(snakemake.params["energy_totals_year"])
        heating_efficiencies = pd.read_csv(fn, index_col=[1, 0]).loc[year]
```

And then add to `add_existing_baseyear` rule definition:

```
params:
    energy_totals_year=config_provider("energy", "energy_totals_year")
```

2024-09-10 19:24 UTC, fneum commented on scripts/build_energy_totals.py
> +    to_drop = to_drop.append(pd.Index(["passenger cars", "passenger car efficiency"]))
simpfliy
```suggestion
    efficiency_keywords = ["space efficiency", "water efficiency"]
    to_drop = idees.columns[~idees.columns.str.contains('|'.join(efficiency_keywords))]
    to_drop = to_drop.append(["passenger cars", "passenger car efficiency"])
```

2024-09-10 19:24 UTC, fneum commented on scripts/build_energy_totals.py
> +    )
```suggestion
    patterns = ["passenger cars", ".*space efficiency", ".*water efficiency"]
    exclude = totals.columns.str.fullmatch("|".join(patterns))
```

2024-09-10 19:24 UTC, fneum commented on scripts/build_energy_totals.py
> +    logger.info(cols)
```suggestion
```

remove or more descriptive logging info

2024-09-10 19:24 UTC, fneum commented on scripts/prepare_sector_network.py
> +    )
similar as above; no `snakemake.config` due to scenario management.

```suggestion
    fn = snakemake.input.heating_efficiencies
    year = int(snakemake.params["energy_totals_year"])
    heating_efficiencies = pd.read_csv(fn, index_col=[0, 1]).swaplevel().loc[year]
```

And add to `perpare_sector_network` rule definition:

```
params:
    energy_totals_year=config_provider("energy", "energy_totals_year")
```

2024-09-10 19:24 UTC, fneum commented on scripts/add_existing_baseyear.py
> +        efficiency = costs.at[boiler_costs_name, "efficiency"]
Throws error in CI:

```
     if heat_system.sector.value == "residential":
       ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
```

2024-09-11 13:25 UTC, merged