Fix myopic optimization for networks with geothermal district heating
PyPSA/pypsa-eur pull request #1453
Opened 2024-12-12 16:08 UTC by cpschau

## Changes proposed in this Pull Request

Geothermal heat for district heating was implemented in #1359. However, it was not working for the myopic code. This PR includes two changes, that fix the issue:

1. The dataframe containing the existing heating distribution was extended to include all provided district heating heat pump sources in `build_existing_heating_distribution`.
2. The indices of the heat pumps built in the predecessing planning horizon (relative to the planning horizon to be optimized) were adjusted for the COP correction in `add_brownfield`. This correction is done to account for the supply temperature dynamics in district heating and should be further adjusted as described in #1451 to depict efficiency gains for heat pumps due to technological learning.

## Checklist

- [ ] I tested my contribution locally and it works as intended.
- [ ] Code and workflow changes are sufficiently documented.
- [ ] Changed dependencies are added to `envs/environment.yaml`.
- [ ] Changes in configuration options are added in `config/config.default.yaml`.
- [ ] Changes in configuration options are documented in `doc/configtables/*.csv`.
- [ ] Sources of newly added data are documented in `doc/data_sources.rst`.
- [ ] A release note `doc/release_notes.rst` is added.

2024-12-13 13:55 UTC, amos-schledorn requested changes
Thanks for spotting this! Just had minor comments. Also, could you update the release notes?

2024-12-13 13:55 UTC, amos-schledorn commented on scripts/add_brownfield.py
> +        & n_p.links.index.str[:-4].isin(n.links_t.efficiency.columns.str[:-4])
Hmm, I would need an additional comment here to follow here :)

2024-12-13 13:55 UTC, amos-schledorn commented on scripts/build_existing_heating_distribution.py
> +        nodal_heat_name_tech[("urban central", f"{heat_pump_source} heat pump")] = 0.0
If you have the time: could you add a comment or two to the function and convert the function header to a docstring?

2025-01-02 14:20 UTC, fneum reviewed
Good to go when @amos-schledorn and my comments addressed.

2025-01-06 11:20 UTC, cpschau commented on scripts/add_brownfield.py
> +        & n_p.links.index.str[:-4].isin(n.links_t.efficiency.columns.str[:-4])
@amos-schledorn Added comments

@fneum The wildcard value is stored and passed as `year` variable, so I used this variable instead.

2025-01-06 11:20 UTC, cpschau commented on scripts/build_existing_heating_distribution.py
> +        nodal_heat_name_tech[("urban central", f"{heat_pump_source} heat pump")] = 0.0
Done

2025-01-09 09:16 UTC, amos-schledorn commented
Hey @cpschau, sorry I didn't see this earlier: in your plot, it looks like the COP for 2030 build year HPs is a bit higher than the COP for 2020 build year HPs in 2030. But maybe I'm reading this wrong?

2025-01-09 10:12 UTC, amos-schledorn commented on scripts/add_brownfield.py
> +        & n_p.links.index.str[:-4].isin(n.links_t.efficiency.columns.str[:-4])
@cpschau so we need this addition to avoid copying heat pumps from `n_p` for which `efficiency=0` at all time in the current iteration (which would happen if, in the current iteration, the fwd temperature is constantly lower-or-equal the heat source temperature)?

2025-01-15 09:32 UTC, cpschau commented
> Hey @cpschau, sorry I didn't see this earlier: in your plot, it looks like the COP for 2030 build year HPs is a bit higher than the COP for 2020 build year HPs in 2030. But maybe I'm reading this wrong?

You are reading it right. For the geothermal heat pumps there is a higher average COP, because the 2030 network comprises new urban central heat buses in Albania, Spain, Ireland, and Montenegro, as the district heating share is increasing from 0 to 0.3 (configurable). At these buses the COPs happen to be higher than the 2020 average.

![Screenshot from 2025-01-15 10-27-12](https://github.com/user-attachments/assets/e200eb37-a886-48e5-9c7f-d533d8d6a80d)

2025-01-15 09:36 UTC, cpschau commented on scripts/add_brownfield.py
> +        & n_p.links.index.str[:-4].isin(n.links_t.efficiency.columns.str[:-4])
Yes!

2025-01-15 10:48 UTC, amos-schledorn commented
> > Hey @cpschau, sorry I didn't see this earlier: in your plot, it looks like the COP for 2030 build year HPs is a bit higher than the COP for 2020 build year HPs in 2030. But maybe I'm reading this wrong?
> 
> You are reading it right. For the geothermal heat pumps there is a higher average COP, because the 2030 network comprises new urban central heat buses in Albania, Spain, Ireland, and Montenegro, as the district heating share is increasing from 0 to 0.3 (configurable). At these buses the COPs happen to be higher than the 2020 average.
> 
> ![Screenshot from 2025-01-15 10-27-12](https://private-user-images.githubusercontent.com/124347782/403353239-e200eb37-a886-48e5-9c7f-d533d8d6a80d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY5MzU1MjksIm5iZiI6MTczNjkzNTIyOSwicGF0aCI6Ii8xMjQzNDc3ODIvNDAzMzUzMjM5LWUyMDBlYjM3LWE4ODYtNDhlNS05YzdmLWQ1MzNkOGQ2YTgwZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDExNVQxMDAwMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MzkwMTM3MThmMGUzYmE4OTFhNTExNWQ4YjEzNGQyMTUzZDAxNmRlOThkYWQzZDFmMmE2YjM2N2RiOTE1MmI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.cKNkELeqW_7tOJJv5sKjSOHCwjv7-IUWeaQhFV4t74U)

Makes sense. Thanks!

2025-01-15 10:49 UTC, amos-schledorn commented
Good to go from my side!

2025-01-15 10:49 UTC, amos-schledorn approved these changes

2025-01-24 08:01 UTC, merged