Custom busmap for clustering
PyPSA/pypsa-eur pull request #193
Opened 2020-09-22 12:55 UTC by eb5194

## Changes proposed in this Pull Request
#124 

Add a custom clustermaps, e.g. when running the same experiment with a different setting, but want to maintain the same clustering obtained from the first run to make results more comparable. Then, you can copy the clustermaps of your favor from "resources/" to "data/" and rename it to "custom_clustermaps_elec_s_{n_clusters}.h5"; and set "custom_clustermaps" in your config file to True.

**ToDo**: Test for an own busmapping, e.g. from a csv file? At the moment, busmap has to be in same format as clustermaps_elec_s_{n_clusters}.h5. Suggestions?

## Checklist

- [ ] I tested my contribution locally and it seems to work fine.
- [ ] Code and workflow changes are sufficiently documented.
- [ ] Newly introduced dependencies are added to `environment.yaml` and `environment.docs.yaml`.
- [ ] Changes in configuration options are added in all of `config.default.yaml`, `config.tutorial.yaml`, and `test/config.test1.yaml`.
- [ ] Changes in configuration options are also documented in `doc/configtables/*.csv` and line references are adjusted in `doc/configuration.rst` and `doc/tutorial.rst`.
- [ ] A note for the release notes `doc/release_notes.rst` is amended in the format of previous release notes.

2020-09-26 10:02 UTC, fneum requested changes
I am aware this is still a draft, but one important suggestion regarding the file handling.

Also, for now keep the {network} wildcard in the filename. It will be removed soon, because all other sectors handled in PyPSA-Eur-Sec.

The custom mapping is from simplified network to clustered network. You can add support for different simplification levels (and consistency) by also adding the `{simpl}` wildcard to the filename.

Custom clustermaps for `simplify_network` rule probably don't make any sense, do they?

2020-09-28 08:21 UTC, fneum commented
> ToDo: Test for an own busmapping, e.g. from a csv file? At the moment, busmap has to be in same format as clustermaps_elec_s_{n_clusters}.h5. Suggestions?

Since you only need the custom busmaps and recalculate linemaps anyhow in `get_clustering_from_busmap(...)` [BTW is the function busmap->linemap unique/deterministic?], you could just provide the busmap as an input `.csv` file rather than the full `.h5` store.

The disadvantage is that you need to take manual action to reuse an existing clustermap generated by `cluster_network` with:

```py
import pandas as pd
with pd.HDFStore('resources/clustermaps_elec_s_X.h5', mode='r') as store:
    store.busmap.to_csv("data/custom_busmaps_elec_s_X.csv")
```

The advantage would be that it is much easier to create manual busmaps in a simple `pd.Series`:

```
name
7932    DE0 0
2332    DE0 0
        ...  
7961    DE0 1
8205    DE0 4
Name: busmap, Length: 317, dtype: object
```

Also, this doesn't store unnecessary data.

Then in `cluster_network` you just load the busmaps:

```py
busmapfornclusters = pd.read_csv(snakemake.input.custom_busmaps)
```

2020-09-28 08:25 UTC, fneum commented
You could also support both variants (`.h5` and `.csv`) by adding switches based on the file ending, but I think it's cleanest to only support `.csv`.

2020-09-29 08:21 UTC, eb5194 commented
> Custom clustermaps for `simplify_network` rule probably don't make any sense, do they? Maybe it does.

No I think it makes no sense to customize the simplify script, unless its used with a number, such as elec_s1024

2020-09-29 08:24 UTC, eb5194 commented
> [BTW is the function busmap->linemap unique/deterministic?]
Yes, should be.

About .csv vs .h5-format; might be worth to include both... not sure yet.

2020-09-29 09:11 UTC, FabianHofmann commented
Just for the convention: I think it would make more sense to name `custom_clustermaps` -> `custom_busmap`. This is what is used in pypsa and makes clear that it refers to spatial clustering (not temporal)

2020-09-29 09:17 UTC, eb5194 commented
> Just for the convention: I think it would make more sense to name `custom_clustermaps` -> `custom_busmap`. This is what is used in pypsa and makes clear that it refers to spatial clustering (not temporal)

In that case, all reference clustermaps that are generated by pypsa-eur in `resources/ `should be renamed to `busmap` as well. Otherwise it will become confusing that pypsa-eur generates "`clustermaps`", but the custom ones are named "`busmap`".

2020-09-29 09:47 UTC, fneum commented
Possible distinction here:

- `clustermaps` for all `.h5` since they include both busmaps and linemaps
- `busmaps` for all `.csv` sind they only include the busmap.

2020-10-09 15:25 UTC, fneum requested changes
Ok, almost there! Tests fail because

```yaml
clustering:
  custom_clustermaps: False
```

is not also in `test/config.test1.yaml` and `config.tutorial.yaml`.
Then all is left to do is going through the checklist (esp. point 5)

2020-10-12 07:56 UTC, eb5194 commented
> Then all is left to do is going through the checklist (esp. point 5)

How about a custom busmap for the sites? I.e. elec_s1000_37m.nc. Then 1000 sites can be read from the custom busmap and the transmission grid is at 37 nodes/one node per country. Of course, in this case both could be customized.

We could also do that in a separate PR.

2020-10-12 08:02 UTC, fneum commented
> How about a custom busmap for the sites?

If you need this, why not. But in this case it should be a separate PR.

2020-11-24 15:28 UTC, fneum commented
status @eb5194, good for another review iteration?

2020-11-25 06:56 UTC, eb5194 commented
> status @eb5194, good for another review iteration?

Should be, yes! Thanks

2020-11-26 16:19 UTC, fneum requested changes
@eb5194 here's a few suggestions to further simplify the code (esp. avoid layered `if-else` in `cluster_network.py` and avoid call of `busmap_for_n_clusters()` in `simplify_network.py`.

The function `clustering_for_n_clusters()` just gets a `custom_busmap=False` flag that triggers loading the alternative `busmapfornclusters`.

2020-11-26 16:19 UTC, fneum commented on scripts/cluster_network.py
> +def clustering_for_n_clusters(n, n_clusters, busmapfornclusters=None, aggregate_carriers=None,
```suggestion
def clustering_for_n_clusters(n, n_clusters, custom_busmap=False, aggregate_carriers=None,
```

2020-11-26 16:19 UTC, fneum commented on scripts/cluster_network.py
> +            busmapfornclusters = busmap_for_n_clusters(n, n_clusters, solver_name, focus_weights, algorithm)
```suggestion
    if custom_busmap:
        busmapfornclusters = (pd.read_csv(snakemake.input.custom_busmap, dtype={'name':'str'})
                              .set_index('name')).squeeze()
        logger.info(f"Imported custom busmap from {snakemake.input.custom_busmap}")
    else:
        busmapfornclusters = busmap_for_n_clusters(n, n_clusters, solver_name, focus_weights, algorithm)
```

2020-11-26 16:19 UTC, fneum commented on scripts/simplify_network.py
> +from cluster_network import clustering_for_n_clusters, cluster_regions, busmap_for_n_clusters
```suggestion
from cluster_network import clustering_for_n_clusters, cluster_regions
```

2020-11-26 16:19 UTC, fneum commented on scripts/simplify_network.py
> +    clustering = clustering_for_n_clusters(n, n_clusters, busmapfornclusters, potential_mode=potential_mode,
```suggestion
    clustering = clustering_for_n_clusters(n, n_clusters, custom_busmap=False, potential_mode=potential_mode,
```

2020-11-26 16:19 UTC, fneum commented on scripts/cluster_network.py
> +        clustering = clustering_for_n_clusters(n, n_clusters, aggregate_carriers=aggregate_carriers,
```suggestion
        custom_busmap = snakemake.config["clustering"]["custom_busmap"]
        clustering = clustering_for_n_clusters(n, n_clusters, custom_busmap, aggregate_carriers,
```

2020-11-26 16:23 UTC, fneum commented
And need to address the two last items of the checklist, i.e.: documentation of configuration settings, add release notes.

2020-12-03 14:17 UTC, merged