simplify_ and cluster_network: clustermaps to csv
PyPSA/pypsa-eur pull request #198
Opened 2020-09-30 07:43 UTC by eb5194

Closes # (if applicable).

## Changes proposed in this Pull Request
Output file `clustermaps` of `simplify_network` and `cluster_network` splitted into seperate output files: `busmap_{network}_s{simpl}`, `busmap_{network}_s{simpl}_{nclusters}`, `linemap_{network}_s{simpl}_{nclusters}`, `linemap_positive_{network}_s{simpl}_{nclusters}` and `linemap_negative_{network}_s{simpl}_{nclusters}`.  The format changed from Hierarchical Data Format (`.h5`) to Comma Seperated Values format (`.csv`) for easier user handling.

Should we save all output files? Or would it be sufficient to save only the busmaps, not the linemaps as they are derived based on the busmapping?

## Checklist

- [x] I tested my contribution locally and it seems to work fine.
- [x] Code and workflow changes are sufficiently documented.
- [x] Newly introduced dependencies are added to `environment.yaml` and `environment.docs.yaml`.
- [x] Changes in configuration options are added in all of `config.default.yaml`, `config.tutorial.yaml`, and `test/config.test1.yaml`.
- [x] Changes in configuration options are also documented in `doc/configtables/*.csv` and line references are adjusted in `doc/configuration.rst` and `doc/tutorial.rst`.
- [x] A note for the release notes `doc/release_notes.rst` is amended in the format of previous release notes.

2020-10-01 16:32 UTC, fneum requested changes
Yes, I like this solution. But please move all references to files to the `Snakefile` and access in scripts via `snakemake.output` or `snakemake.input`.

2020-10-01 16:32 UTC, fneum commented on doc/release_notes.rst
> +* Output of `simplify_network.py` and `cluster_network.py` changed from Hierarchical Data Format (.h5) to Comma-Separated Values format (.csv), i.e. all busmaps and linemaps.
```suggestion
* The mappings for clustered lines and buses produced by the ``simplify_network`` and ``cluster_network`` rules changed from Hierarchical Data Format (.h5) to Comma-Separated Values format (.csv) (`#198 <https://github.com/PyPSA/pypsa-eur/pull/198>`_)
```

2020-10-01 16:39 UTC, fneum commented
> Should we save all output files? Or would it be sufficient to save only the busmaps, not the linemaps as they are derived based on the busmapping?

I think we should keep both busmaps and linemaps because it simplifies debugging and doesn't take up disk space or anything. I am not sure how useful `*_positive/negative` are. If you don't think they are interesting --> remove.

2020-10-01 16:41 UTC, fneum commented
Another note: If pypsa-eur-sec should be compatible with pypsa-eur v0.3 (which incorporates changes in this PR), there should be another PR to the pypsa-eur-sec repository.

The rules https://github.com/PyPSA/pypsa-eur-sec/blob/master/scripts/prepare_sector_network.py and https://github.com/PyPSA/pypsa-eur-sec/blob/master/scripts/add_existing_baseyear.py access the clustermaps from the pypsa-eur subworkflow. It should only be a handful of lines of code.

2020-10-02 06:44 UTC, eb5194 commented
> > Should we save all output files? Or would it be sufficient to save only the busmaps, not the linemaps as they are derived based on the busmapping?
> 
> I think we should keep both busmaps and linemaps because it simplifies debugging and doesn't take up disk space or anything. I am not sure how useful `*_positive/negative` are. If you don't think they are interesting --> remove.

I suggest make it subject to configuration. Might be useful at some point, and then you won't need to change the code.

2020-10-02 10:39 UTC, eb5194 commented
> Another note: If pypsa-eur-sec should be compatible with pypsa-eur v0.3 (which incorporates changes in this PR), there should be another PR to the pypsa-eur-sec repository.
> 
> The rules https://github.com/PyPSA/pypsa-eur-sec/blob/master/scripts/prepare_sector_network.py and https://github.com/PyPSA/pypsa-eur-sec/blob/master/scripts/add_existing_baseyear.py access the clustermaps from the pypsa-eur subworkflow. It should only be a handful of lines of code.
> 
> We then need to coordinate a pypsa-eur and pypsa-eur-sec release.

Thanks Fabian for pointing this out. Suggestion in https://github.com/PyPSA/pypsa-eur-sec/pull/70. Worked for me.

2020-10-02 10:52 UTC, fneum approved these changes

2020-10-02 10:53 UTC, merged