[DNMY] Opsd renewable ppls
PyPSA/pypsa-eur pull request #203
Opened 2020-10-19 11:16 UTC by eb5194

Closes #192 

## Changes proposed in this Pull Request

add renewable assets given in a OPSD data publication to the network. Data is downloaded in powerplantmatching, so if new countries become available, they have to be added there.

If estimate_renewable_capacities is applied, then available renewable capacities are overwritten for those countries where precise lat and lon are given (which at the moment is false for e.g. Poland).

**works only with the latest version of powerplantmatching**. (19.10.2020 ?)

**updated PR of #192 because target branch was not `master`**

## Checklist

- [x] I tested my contribution locally and it seems to work fine.
- [x] Code and workflow changes are sufficiently documented.
- [x] Newly introduced dependencies are added to `environment.yaml` and `environment.docs.yaml`.
- [x] Changes in configuration options are added in all of `config.default.yaml`, `config.tutorial.yaml`, and `test/config.test1.yaml`.
- [x] Changes in configuration options are also documented in `doc/configtables/*.csv` and line references are adjusted in `doc/configuration.rst` and `doc/tutorial.rst`.
- [x] A note for the release notes `doc/release_notes.rst` is amended in the format of previous release notes.

2020-11-24 15:11 UTC, fneum commented
ready for review @eb5194?

2020-11-24 15:15 UTC, fneum commented
> works only with the latest version of powerplantmatching. (19.10.2020 ?)

DNMY is because https://github.com/FRESNA/powerplantmatching/commit/38b075def3d866be226b97fca7cc4805242ec108 is not released yet.

Needs a future release 0.4.6 of `powerplantmatchin` which should be reflected in the `environment.*.yaml` files @eb5194.

2020-11-24 15:15 UTC, eb5194 commented
> ready for review @eb5194?

for me it's working as it is, so yes. thanks!

2020-11-24 15:18 UTC, FabianHofmann commented
Just let me update the ppm code. I will introduce some functionality to make this more slim

2020-11-26 09:46 UTC, FabianHofmann requested changes

2020-11-26 09:46 UTC, FabianHofmann commented on scripts/add_electricity.py
> +    return n.buses.loc[buses].iloc[idx].name + ' ' + tech
This is better done using the `scipy.spatial.KDTree`

2020-11-26 09:46 UTC, FabianHofmann commented on scripts/add_electricity.py
> +                    .format(country, n.generators.loc[mapping.index].groupby('carrier').sum().p_nom))
```suggestion
def attach_OPSD_renewables(n):
    available = ['DE', 'FR', 'PL', 'CH', 'DK', 'CZ', 'SE', 'GB']
    countries = set(available) & set(n.buses.country)
    tech_map = (snakemake.config['electricity']
                 .get('include_renewable_capacities_from_OPSD', {}))
    logger.info(f'Using OPSD renewable capacities in {", ".join(countries)}.')

    df = pd.concat([pm.data.OPSD_VRE_country(c) for c in countries])
    df = df.query('Fueltype in @techs').powerplant.convert_country_to_alpha2()
    technology_b = ~df.Technology.isin(['Onshore', 'Offshore'])
    df['Fueltype'] = df.Fueltype.where(technology_b, df.Technology)

    for fueltype, carrier_like in tech_map.items():
        gens = n.generators[lambda df: df.carrier.str.contains(carrier_like)]
        buses = n.buses.loc[gens.bus.unique()]
        gens_per_bus = gens.groupby('bus').p_nom.count()

        caps = map_country_bus(df.query('Fueltype == @fueltype'), buses)
        caps = caps.groupby(['bus']).Capacity.sum()

        n.generators.p_nom.update(gens.bus.map(caps).dropna())
```

Could you try out this function? (uses the current ppm master). It should include all the functionality from above

2020-11-26 09:46 UTC, FabianHofmann commented on scripts/add_electricity.py
> +                    pd.Series((capacities.query('Fueltype in @ppm_fueltype').Capacity/len(techs)).values,
Here you divide by `len(techs)`. This assumes that all techs are at all buses, right?. However, there are cases where you have only onwind or only offwind (not both) at a bus.

2020-11-26 09:46 UTC, FabianHofmann commented on scripts/add_electricity.py
> +                pool_buses = multiprocessing.Pool(processes=4)
The pooling is nicely implemented, but when using `KDTree` (which is super fast) it is not necessary.

2020-11-26 09:46 UTC, FabianHofmann commented on scripts/add_electricity.py
> +                .format(country))
not necessarily right?

2020-12-02 17:39 UTC, FabianHofmann commented
I'm closing this in the favour of #212

2020-12-02 17:39 UTC, closed without merging