Keep links to store components when using ATK wildcard
PyPSA/pypsa-eur pull request #214
Opened 2021-01-10 12:30 UTC by chiaroo

The new ATK wildcard removes all lines + links without further distinction; however, since storage options are now modeled as store components, the links to and from the the storage units for (dis)charge are eliminated as well. Thus, the storage options drop out of the optimisation.
Especially when only allowing renewables as generation sources, optimisation may become infeasible for a high temporal resolution (capacity factors = 0 for certain hours; no further options to serve the load).
This issue does not arise with the ATKc wildcard, since bus0 and bus1 of the (dis)charge links share the same country code.

The proposed change is a very quick fix in the enforce_autarky function, solely removing DC links.

Closes # (if applicable).

## Changes proposed in this Pull Request

enforce_autarky() in prepare_network.py

## Checklist

- [x] I tested my contribution locally and it seems to work fine.
- [x] Code and workflow changes are sufficiently documented.
- [ ] Newly introduced dependencies are added to `envs/environment.yaml` and `envs/environment.docs.yaml`.
- [ ] Changes in configuration options are added in all of `config.default.yaml`, `config.tutorial.yaml`, and `test/config.test1.yaml`.
- [ ] Changes in configuration options are also documented in `doc/configtables/*.csv` and line references are adjusted in `doc/configuration.rst` and `doc/tutorial.rst`.
- [ ] A note for the release notes `doc/release_notes.rst` is amended in the format of previous release notes.

2021-01-10 12:59 UTC, fneum requested changes
@chiaroo, great catch! Filtering by the carrier is the way to go. I have made a suggestion on how to make the changes more compact.

2021-01-10 12:59 UTC, fneum commented on scripts/prepare_network.py
> +                links_rm.append(i)
This is a more compact formulation:
```suggestion
        links_rm = n.links.loc[n.links.carrier=="DC"].index
```
You would also remove initialisation of `links_rm` further up.

2021-01-10 13:56 UTC, chiaroo commented
@fneum, thank you! Your suggestion has been commited and the initialisation of links_rm has been removed.

2021-01-11 09:27 UTC, fneum approved these changes

2021-01-11 09:27 UTC, merged