Eia hydro
PyPSA/pypsa-eur pull request #347
Opened 2022-03-28 10:05 UTC by fneum

Closes #324.

## Changes proposed in this Pull Request

- [ ] help wanted to automate download without API

## Checklist

- [ ] I tested my contribution locally and it seems to work fine.
- [ ] Code and workflow changes are sufficiently documented.
- [ ] Newly introduced dependencies are added to `envs/environment.yaml` and `envs/environment.docs.yaml`.
- [ ] Changes in configuration options are added in all of `config.default.yaml`, `config.tutorial.yaml`, and `test/config.test1.yaml`.
- [ ] Changes in configuration options are also documented in `doc/configtables/*.csv` and line references are adjusted in `doc/configuration.rst` and `doc/tutorial.rst`.
- [ ] A note for the release notes `doc/release_notes.rst` is amended in the format of previous release notes.

2022-03-28 20:59 UTC, euronion requested changes
Any idea why the historic EIA values changed? It's mostly a few percent (e.g. Austria), but some of the value changes are > 15% (mostly for countries with very low / low hydro generation)

![image](https://user-images.githubusercontent.com/42553970/160484199-723e0d22-a640-471b-9011-da49deec7f04.png)

Also needs an update to the RELEASE_NOTES (less databundle dependency, more data in repo).

Else LGTM.

2022-03-28 20:59 UTC, euronion commented on scripts/build_hydro_profile.py
> +cc = coco.CountryConverter()
Change of dependency in `environment.yaml` from PyPSA-EUR-Sec dep to PyPSA-EUR dep.

2022-03-28 20:59 UTC, euronion commented on scripts/build_hydro_profile.py
> +    df.index = cc.convert(df.index, to='iso2')
This throws three warnings
```
Europe not found in regex
Germany, East not found in regex
Germany, West not found in regex
```

Maybe also exclude those similarly to line 81?

2022-03-29 07:18 UTC, fneum commented
No idea where the difference in EIA data come from.

2022-03-29 07:34 UTC, merged