Enable scneario management for different configs
PyPSA/pypsa-eur pull request #413
Opened 2022-09-08 07:54 UTC by FabianHofmann

From the release notes:

The software now supports running the workflow with different settings within the same directory. A new config section ``run`` was created that specifies under which scenario ``name`` the created resources, networks and results should be stored. If ``name`` is not specified, the workflow uses the default paths. The entry ``dedicated_cutout`` specifies whether the run should use cutouts from the default root directory and use run-specific cutouts.

@fneum @p-glaum  any suggestion on how to rename `dedicated_cutouts`? No so happy with this key...

Note this is a non-breaking change.

## Checklist

- [x] I tested my contribution locally and it seems to work fine.
- [x] Code and workflow changes are sufficiently documented.
- [x] Changes in configuration options are also documented in `doc/configtables/*.csv` and line references are adjusted in `doc/configuration.rst` and `doc/tutorial.rst`.
- [x] A note for the release notes `doc/release_notes.rst` is amended in the format of previous release notes.

2022-09-08 18:39 UTC, FabianHofmann commented on Snakefile
> +        europe_shape="resources/" + RDIR + "europe_shape.geojson",
The shapes are dependent on the selected countries so I maid it dependent on the run. You are right the `europe_shape` is redundant here, but I'd keep it this way for a consistent data flow.

2022-09-09 06:30 UTC, p-glaum commented on Snakefile
> +        nuts3_shapes="resources/" + RDIR + "nuts3_shapes.geojson"
here I meant only to comment on the nuts3_shapes

2022-09-09 06:32 UTC, p-glaum commented on Snakefile
> +        europe_shape="resources/" + RDIR + "europe_shape.geojson",
ah okay. here I only meant to comment on the Europe shape. But for consistency it makes sense

2022-09-12 15:08 UTC, FabianHofmann commented
@fneum any objection to merge this?

2022-09-13 06:54 UTC, fneum requested changes
Nice! Especially, since it keeps paths as they were if no run-name is specified!

Just a few minor comments:

Could you document new `run` options also at

https://github.com/PyPSA/pypsa-eur/blob/master/doc/configtables/toplevel.csv

2022-09-13 06:54 UTC, fneum commented on Snakefile
> +RDIR = run.get("name", "") + "/" if run.get("name", "") else ""
shorter alternative?
```suggestion
RDIR = run["name"] + "/" if run.get("name") else ""
```

2022-09-13 06:54 UTC, fneum commented on doc/configuration.rst
> +The ``run`` section is used for running and storing scenarios with different configurations which are not covered by :ref:`wildcards`. It determines the path at which resources, networks and results
```suggestion
The ``run`` section is used for running and storing scenarios with different configurations which are not covered by :ref:`wildcards`. It determines the path at which resources, networks and results are stored. Therefore the user can run different configurations within the same directory. If a run with a non-empty name should use cutouts shared across runs, set ``shared_cutouts`` to `true`.       
```

2022-09-13 07:47 UTC, FabianHofmann commented on Snakefile
> +RDIR = run.get("name", "") + "/" if run.get("name", "") else ""
good one :)

2022-09-13 07:48 UTC, FabianHofmann commented on config.default.yaml
> +  dedicated_cutouts: True # set to false to use the default cutout(s)
yes, that's a good idea

2022-09-13 13:16 UTC, merged