doc: update config section
PyPSA/pypsa-eur pull request #685
Opened 2023-06-28 08:04 UTC by FabianHofmann

Update the documentation's config section. Pull out config comments to documentation.

2023-07-05 13:44 UTC, FabianHofmann commented
@fneum @lisazeyen could one of you also have a look? In particular, at the documentation of the sector section at https://pypsa-eur--685.org.readthedocs.build/en/685/configuration.html#sector

2023-07-05 20:12 UTC, fneum requested changes
Excellent! Super helpful!

I have made small adjustments here and there.

One thing to be careful about: When the documentation says percentage, I would put e.g. 20.7 for 20.7%, but in most cases the input requires 0.207. Maybe one could clarify this.

My other comment is stylistic. Could you check if it makes sense to adjust the column widths of the tables and give more width to the description?

2023-07-05 20:12 UTC, fneum commented on doc/configtables/sector.csv
> +co2_spatial,--,"{true, false}","„Add option to spatially resolve carrier representing stored carbon dioxide. This allows for more detailed modelling of CCUTS, e.g. regarding the capturing of industri
```suggestion
co2_spatial,--,"{true, false}","Add option to spatially resolve carrier representing stored carbon dioxide. This allows for more detailed modelling of CCUTS, e.g. regarding the capturing of industrial process emissions, usage as feedstock for electrofuels, transport of carbon dioxide, and geological sequestration sites."

```

2023-07-05 20:12 UTC, fneum commented on doc/configtables/sector.csv
> +co2network,--,"{true, false}",Add option for planning a new carbon dioxide network
```suggestion
co2network,--,"{true, false}",Add option for planning a new carbon dioxide transmission network

```

2023-07-05 20:12 UTC, fneum commented on doc/configtables/sector.csv
> +hydrogen_underground_storage_locations,,"{onshore, nearshore, offshore}","„The location where hydrogen underground storage can be located. Onshore, nearshore, offshore means it must be located more t
```suggestion
hydrogen_underground_storage_locations,,"{onshore, nearshore, offshore}","The location where hydrogen underground storage can be located. Onshore, nearshore, offshore means it must be located more than 50 km away from the sea, within 50 km of the sea, or within the sea itself respectively."

```

2023-07-05 20:12 UTC, fneum commented on doc/configtables/sector.csv
> +min_part_load_methanolisation,per unit of p_nom ,float,The minimum unit dispatch (p_min_pu) for the methanolisation process
```suggestion
min_part_load_fischer_tropsch,per unit of p_nom ,float,The minimum unit dispatch (``p_min_pu``) for the Fischer-Tropsch process
min_part_load_methanolisation,per unit of p_nom ,float,The minimum unit dispatch (``p_min_pu``) for the methanolisation process

```

2023-07-05 20:12 UTC, fneum commented on doc/configtables/sector.csv
> +electricity_distribution_grid,--,"{true, false}",Add a electricity distribution grid
```suggestion
electricity_distribution_grid,--,"{true, false}",Add a simplified representation of the exchange capacity between transmission and distribution grid level through a link.
```

2023-07-05 20:12 UTC, fneum commented on doc/configtables/sector.csv
> +electricity_distribution_grid_cost_factor,,,Multiplies the investment cost of the electricity distribution grid in data/costs.csv
```suggestion
electricity_distribution_grid_cost_factor,,,Multiplies the investment cost of the electricity distribution grid

```

2023-07-05 20:12 UTC, fneum commented on doc/configtables/sector.csv
> +H2_retrofit_capacity_per_CH4,--,float,The ratio for H2 capacity per original CH4 capacity of retrofitted pipelines
```suggestion
H2_retrofit,--,"{true, false}","Add option for retrofiting existing pipelines to transport hydrogen. "
H2_retrofit_capacity_per_CH4,--,float,"The ratio for H2 capacity per original CH4 capacity of retrofitted pipelines. The `European Hydrogen Backbone (April, 2020) p.15 <https://gasforclimate2050.eu/wp-content/uploads/2020/07/2020_European-Hydrogen-Backbone_Report.pdf>`_ 60% of original natural gas capacity could be used in cost-optimal case as H2 capacity."
```

2023-07-05 20:12 UTC, fneum commented on doc/configtables/sector.csv
> +gas_distribution_grid_cost_factor,,,Multiplies the investment cost of the gas distribution grid in data/costs.csv
```suggestion
gas_distribution_grid_cost_factor,,,Multiplier for the investment cost of the gas distribution grid

```

2023-07-05 20:12 UTC, fneum commented on doc/configtables/industry.csv
> +DRI_fraction,--,Dictionary with planning horizons as keys.,The fraction of the primary route converted to DRI + EAF
```suggestion
DRI_fraction,--,Dictionary with planning horizons as keys.,The fraction of the primary route DRI + EAF

```

2023-07-05 20:12 UTC, fneum commented on doc/configtables/industry.csv
> +HVC_chemical_recycling_fraction,--,float,The fraction of today's high value chemicals (HVC) produced using chemical recycling
```suggestion
HVC_primary_fraction,--,float,The fraction of high value chemicals (HVC) produced via primary route
HVC_mechanical_recycling_fraction,--,float,The fraction of high value chemicals (HVC) produced using mechanical recycling
HVC_chemical_recycling_fraction,--,float,The fraction of high value chemicals (HVC) produced using chemical recycling

```

2023-07-05 20:12 UTC, fneum commented on doc/configtables/industry.csv
> +MWh_elec_per_tHVC_chemical_recycling,MWh/tHVC,float,"The energy amount of electricity needed to produce a ton of high value chemical (HVC) using chemical recycling. Value are based on pyrolysis and e
```suggestion
MWh_elec_per_tHVC_chemical_recycling,MWh/tHVC,float,"The energy amount of electricity needed to produce a ton of high value chemical (HVC) using chemical recycling. The default value is based on pyrolysis and electric steam cracking. From `Material Economics (2019) <https://materialeconomics.com/latest-updates/industrial-transformation-2050>`_, page 125"

```

2023-07-13 08:26 UTC, FabianHofmann commented
Hey @virio-andreyana, there are still some unresolved issues. Would you look into them?

2023-07-13 09:39 UTC, virio-andreyana commented on doc/configtables/sector.csv
> +transport_heating_deadband_lower,°C,float,"The maximum temperature in the vehicle. At higher temperatures, the energy required for cooling in the vehicle increases."
```suggestion
transport_heating_deadband_upper,°C,float,"The maximum temperature in the vehicle. At higher temperatures, the energy required for cooling in the vehicle increases."
transport_heating_deadband_lower,°C,float,"The minimum temperature in the vehicle. At lower temperatures, the energy required for heating in the vehicle increases."

```

2023-07-13 11:04 UTC, virio-andreyana commented
Okay, so the simple suggestion have been added. Now, only a few problem is left.

> One thing to be careful about: When the documentation says percentage, I would put e.g. 20.7 for 20.7%, but in most cases the input requires 0.207. Maybe one could clarify this.

Hmm, I believe that the reader is smart enough to know how the meaning of the percentage works. So long as they see the config default value.

> My other comment is stylistic. Could you check if it makes sense to adjust the column widths of the tables and give more width to the description?

I could try that, maybe by shortening the column for the attribute name, and values

2023-07-13 11:05 UTC, FabianHofmann commented
thanks @virio-andreyana, perhaps we use `share` instead of `percentage`?

2023-07-14 11:35 UTC, FabianHofmann commented
@fneum would you be fine with merging?

2023-07-14 11:35 UTC, fneum commented
The CSVs now have quite a few empty lines. Might cause problems.

2023-07-14 11:35 UTC, fneum commented
Otherwise, yes!

2023-07-14 11:47 UTC, FabianHofmann commented
> The CSVs now have quite a few empty lines. Might cause problems.

@fneum thanks for looking over
@virio-andreyana this seems to be the last remaining issue

2023-07-14 12:09 UTC, virio-andreyana commented
> The CSVs now have quite a few empty lines. Might cause problems.

Actually this is a dilemma. So what I wanted to achieve is to have all of the table to have the same spacing. But since some attribute have letters longer than 22 letters, the table shifts to the right. Making the room for the description smaller.

This is the case especially for sector.csv and industry.csv

2023-07-17 15:37 UTC, FabianHofmann commented
> > The CSVs now have quite a few empty lines. Might cause problems.
> 
> Actually this is a dilemma. So what I wanted to achieve is to have all of the table to have the same spacing. But since some attribute have letters longer than 22 letters, the table shifts to the right. Making the room for the description smaller.
> 
> This is the case especially for sector.csv and industry.csv

Sound reasonable. Let's keep the extra lines, then. In the docs it looks good.

2023-07-17 16:18 UTC, merged