Adding CHPs to the existing heating baseyear
PyPSA/pypsa-eur pull request #907
Opened 2024-01-31 16:26 UTC by toniseibold

Closes # (if applicable).

## Changes proposed in this Pull Request

## Checklist

- [ ] I tested my contribution locally and it seems to work fine.
- [ ] Code and workflow changes are sufficiently documented.
- [ ] Changed dependencies are added to `envs/environment.yaml`.
- [ ] Changes in configuration options are added in all of `config.default.yaml`.
- [ ] Changes in configuration options are also documented in `doc/configtables/*.csv`.
- [ ] A release note `doc/release_notes.rst` is added.

2024-02-10 13:14 UTC, fneum commented
- hydro and waste are dropped later anyways, hence I dropped them from the powerplant query
- `skipna=True` in mean calculation is not required as this is already the default behaviour
- `try-except` block for lifetimes was not required in my case; if it is needed, I would implement as `if-else` block
- hardcoded heat efficiency (0.71) was removed by using the backpressure coefficient (https://ens.dk/sites/ens.dk/files/Analyser/technology_data_catalogue_for_el_and_dh.pdf, page 21: "The Cb -coefficient (backpressure coefficient) is defined as the maximum power generation capacity in backpressure mode divided by the maximum heat production capacity (including flue gas condensation if applicable)")
- read custom powerplants here, rather than in `build_powerplants` rule.
- I added a mechanism to exclude small CHPs below 500 kW (threshold debatable)
- I use the backpressure coefficient `c_b` for calculating the heat efficiency of power-driven CHPs and followed roughly your approach for strongly heat-driven CHPs while adjusting the split and giving some upper limits for `c_b` and `Efficiency` depending on `efficiency-heat`.
- It should be fine for `DateIn` and `DateOut` to be floats.
- There was a bug which only used the first capacity value in a pandas.Series (`p_nom=capacity[0],` and `capacity[0] / costs.at[key, "efficiency"]`)

TODOs

- [ ] Double-check my changes
- [ ] Handle Fueltypes Other/Waste (relatively large capacity dropped, also linked to duplicates in `pypsa-ariadne` PR)
- [ ] Potentially: keep oil CHPs and use gas CHP for techno-economic data
- [ ] Test run with capacity and energy output comparison to historical statistics.

2024-02-14 16:24 UTC, toniseibold commented
in `add_existing_baseyear.py` why are oil CHPs kept?
```
    if "H" in snakemake.wildcards.sector_opts.split("-"):
        df_agg = df_agg.query("Set != 'CHP' or Fueltype == 'Oil'")
```
Oil and waste CHPs are now kept in the heating sector.

2024-02-16 09:31 UTC, fneum approved these changes
This looks good. Maybe add a release note to `doc/release_notes.rst` and remove the accidental file path added.

2024-02-16 09:31 UTC, fneum commented on scripts/add_existing_baseyear.py
> +    # n = pypsa.Network('/home/toni-seibold/Documents/CHP/pypsa-ariadne/results/240209-365H-fixcoalco2/prenetworks/elec_s_22_lv1.2__365H-T-H-B-I-A_2020.nc')
remove accidental addition

2024-02-16 14:21 UTC, fneum requested changes
one minor item left, otherwise good to go

2024-02-16 14:21 UTC, fneum commented on scripts/add_existing_baseyear.py
> +            df_agg.query("Industry" == False, inplace=True)
```suggestion
    elif "I" not in snakemake.wildcards.sector_opts.split("-") and "Industry" in df_agg.columns:
         df_agg.query("not Industry", inplace=True)
```
very minor :)

But the code should check for existence of "Industry" column, as this cannot be assumed outside the ariadne context.

2024-02-16 14:21 UTC, fneum commented on scripts/add_existing_baseyear.py
> +            chp.query("Industry == False", inplace=True)
```suggestion
            chp.query("not Industry", inplace=True)
```
this should also work.

2024-02-20 08:41 UTC, toniseibold commented
Installed capacity of CHP plants in Germany 2020:
```
urban central coal CHP                  24.096386
urban central gas CHP                 1292.031899
urban central gas CHP CC                 0.000000
urban central lignite CHP              561.611424
urban central solid biomass CHP         42.487920
urban central solid biomass CHP CC       0.000000
```

Heating supply 
```
urban central air heat pump             4.255723e-06
urban central gas CHP                   4.075471e-06
urban central gas CHP CC                1.599523e-06
urban central gas boiler                8.522301e+07
urban central resistive heater          5.342906e-06
urban central solar thermal             8.890480e-07
urban central solid biomass CHP         6.361950e+03
```

2024-05-22 14:14 UTC, lindnemi commented
please add the CHPs in add_existing_power and not in add_existing_heating (because of the differences in the grouping year logic)

2024-05-22 14:15 UTC, lindnemi commented
- [ ] also make sure not to add power-only biomass plants twice

2024-05-24 10:11 UTC, merged